print("Hello, World!")
print("Hello, World!2")
print("Hello, World!3")
print("Hello, World!4")
print("Hello, World!5")
print("Hello, World!6")
print("Hello, World!7")
print("Hello, World!8")
print("Hello, World!9")
print("Hello, World!10")
    